seed_everything: 1234
data:
  meta_train: "/path/to/metadata/file"
  meta_valid: "/path/to/metadata/file"
  batch_size: 32
  symbols_lang: "py_ex"
  text_cleaners: ["basic_cleaners"]
  speaker_item_idx: 1
model:
  mask_padding: true
  n_frames_per_step: 3
  multi_speaker: true
  n_spker: 4
  spker_embedding_dim: 64
  speaker_classifier:
    class_path: model.layers.AdversarialClassifier
    init_args:
      in_dim: 512
      out_dim: 4
  symbols_embedding_dim: 512
  freeze_text: false
  load_pretrained_text: /path/to/load/pretrained/encoder
  encoder:
    class_path: model.encoder.Encoder
    init_args:
      encoder_n_convolutions: 3
      encoder_embedding_dim: 512
      encoder_kernel_size: 5
  decoder:
    class_path: model.decoder.Decoder
    init_args:
      input_ctx_dim: 576
      attention_rnn_dim: 1024
      attention_dim: 128
      attention_location_n_filters: 32
      attention_location_kernel_size: 31
      decoder_rnn_dim: 1024
      prenet_dim: 256
      max_decoder_steps: 1000
      gate_threshold: 0.5
      p_attention_dropout: 0.1
      p_decoder_dropout: 0.1
  postnet:
    class_path: model.postnet.Postnet
    init_args:
      postnet_embedding_dim: 512
      postnet_n_convolutions: 5
      postnet_kernel_size: 5
optimizer:
  lr: 0.001
  weight_decay: 0.000001
lr_scheduler:
  gamma: 0.998
trainer:
  gpus: [0, 1]
  accelerator: "ddp"
  benchmark: false
  gradient_clip_val: 1.0
  check_val_every_n_epoch: 1
  callbacks: 
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args:
        log_momentum: true
  logger: 
    class_path: pytorch_lightning.loggers.TestTubeLogger
    init_args:
      save_dir: "tt_logs"
      name: "my_exp_name"
      version: 0
  weights_summary: "full"
  precision: 32
  profiler: "simple"